### ISSUE TITLE
Deployment target iOS 8.0, should be 7.0?

### ISSUE THREAD

**Issue by Evaugh** [artman/Signals#10]
Hi artman,

Thanks for this awesome library. The documentation says this library requires iOS 7.0 but the podspec targets iOS 8.0. Is iOS 8.0 required and if not, can the target be lowered to 7.0?

**Comment by artman** [comment]
iOS8 is required if you use it via pods, since embedded frameworks are only supported in iOS8. You can use it with iOS7 if you integrate manually.
