### ISSUE TITLE
ListenPastOnce?

### ISSUE THREAD

**Issue by ReneB** [artman/Signals#11]
Would it be useful to have a ListenPastOnce function as well? I'm currently using Signals for creating some data in a remote backend and listening for the return message, but that message might have been received before the `create()` function returns (slim chance, but chance nonetheless). However, I definitely want the trigger to occur only once.

I could code this and submit a PR, but maybe you've got different ideas so I thought I'd check before coding.

**Comment by artman** [comment]
Makes perfect sense, go for it!

**Comment by ReneB** [comment]
Just a heads up: I'll probably get around to doing this today or later this week.
