### ISSUE TITLE
Would it be possible to add a numListeners property [please]?

### ISSUE THREAD

**Issue by josephbeuysmum** [artman/Signals#14]
Firstly, thanks for this library, very useful. Secondly, I'm putting together a SignalsService that can be dependency injected, and privately create/fire/delete Signals, and would be very handy in that context for each Signal to have a numListeners:Int property. No drama if not deemed appropriate, I'll just create a Dictionary of Ints in my own Service if not. JBM.

**Comment by artman** [comment]
Thanks for the suggestion. You currently already can use `signal.listeners.count` for this.

**Comment by josephbeuysmum** [comment]
Whoops. Sorry! Thanks. JBM.
