### ISSUE TITLE
Document changes across releases

### ISSUE THREAD

**Issue by fractious** [artman/Signals#24]
Thanks for sharing this with the world. I'm only making light use of it at present but it seems to work very nicely.

Could you create a changelog file that documents the changes across releases, that would be very helpful.

Thanks.

**Comment by fractious** [comment]
Ah, I see there are some helpful notes at https://github.com/artman/Signals/releases.

Would you consider adding a changelog that goes into a little more detail?

**Comment by artman** [comment]
Added PR #26
