### ISSUE TITLE
removeListener removed?

### ISSUE THREAD

**Issue by korgx9** [artman/Signals#36]
When I updated to the new version, all removeListener methods became undefined. Is it was renamed or removed?

**Comment by artman** [comment]
removeListener is still there if you code against the latest 3.0.0 release. The master branch is currently unstable as I'm updating this for Swift 3 so I'd go with the actual releases.

**Comment by PranKe01** [comment]
Looks like it is called ".cancelSubscription(for: " now... Would be nice if it would be included in the docs.
