### ISSUE TITLE
Support for Swift 3.0?

### ISSUE THREAD

**Issue by RafaelPlantard** [artman/Signals#37]
Is it possible review my PR #38 ?

**Comment by josephbeuysmum** [comment]
Hey Rafael, I'm on artman/signals 3.0.0 and having a similar problem - 61 issues, all seemingly relating to Swift 3.0 upgrade. I'll make changes locally for now, but will keep checking back to see if Tuomas has accepted your PR, rather than do one myself.

**Comment by artman** [comment]
Sorry guys, I've been super busy with work. I do have a branch locally that update Signals to Swift 3 and revamps the API. I'll try to get it up as soon as possible.

**Comment by josephbeuysmum** [comment]
Thank Tuomas, nice to know you're still out there.

**Comment by coolnalu** [comment]
@artman we use it a lot! It's a really neat library and much better than GCP.

**Comment by RafaelPlantard** [comment]
@artman is possible create an release tagged version with full support to Swift 3? I'm working with Podspec and in it is not possible point to branches. Can help me?

**Comment by artman** [comment]
I've got my Swift3 version almost ready to go. Will try to update it by the end of the day.

**Comment by RafaelPlantard** [comment]
Oh @artman that's is great... Thanks...

**Comment by josephbeuysmum** [comment]
nice

**Comment by artman** [comment]
Added PR #41 to get to Swift 3. I did a full revamp of the API to make it more Swifty. Let me know what you think.

**Comment by artman** [comment]
Version 4.0 with Swift 3 support published.

**Comment by josephbeuysmum** [comment]
Thanks Tuomas
