### ISSUE TITLE
Method listenPast should signal error when retainLastData set to false

### ISSUE THREAD

**Issue by xperienced** [artman/Signals#43]
Method listenPast doesn't work with signals that don't retain last data but it doesn't prevent from using it which is causing hard to track issues, especially when you're migrating from old version of this library. There should also be an explanation that you should use listen instead.

**Comment by artman** [comment]
This is resolved in release 5.0. Singnals will now throw an assertion failure for debug builds in case you're observingPast on a Singnal that doesn't retain it's last data.
