### ISSUE TITLE
New Tag Needed

### ISSUE THREAD

**Issue by netizen01** [artman/Signals#45]
Hiya!
Love this lib. I have it as a dependency for a few of my own libs.
Wanting to add support for the Swift Package Manager and discovered that you need to push a new tag to this repo to mark where the Package.swift file becomes available (it came in post 4.0.0 tag).

Can you tag the latest as 4.0.1 or something?

Thanks!

**Comment by artman** [comment]
Sorry for the slow response. Tagged master with 4.0.1.
