### ISSUE TITLE
Cleanest way to set up a subscriber to only observe new(distinct) values instead of all of them?

### ISSUE THREAD

**Issue by DimaVartanian** [artman/Signals#47]
If I have a `Signal<Int>` and the value is currently `1`, then it fires with another `1`, I want certain observers not to respond to it (this would of course require the use of `retainLastData`). The closest thing I see to satisfying this use case would be the use of `filter` when setting up the observation, but it doesn't really work because the only argument is the new value, not the old value to compare and filter against. Is there something I'm missing? If this currently isn't possible, I have a few ideas:

1. Add this functionality into a separate `fire` method, such as `fireIfNew`. This would enforce the constraint on the publisher side if you want to make sure subscribers don't get repeated events for the same value. This is not the most flexible approach so can't be the main change if it happens at all.

2. This seems like a natural candidate for something you can add to `filter`. One way would be to add another parameter to the filter block for the previous value, something like `previousData`. This unfortunately does add a parameter to the `filter` API that not everyone would use.

3. Another solution would be to add this as a chainable modifier method to `SignalSubscription` alongside filter, which then sets an internal flag that can be checked at the same time filter is run. So the method would look something like `ignoreDuplicates()` 

`networkLoader.onProgress.subscribe(on: self) { (progress) in }.filter { $0 == 1.0 }.ignoreDuplicates()`

4. Seems like the cleanest solution would be to add another argument to the subscribe methods with a default value, something like `distinctOnly = false` which would make this a backwards compatible change as the method signature wouldn't need to change to external users of the framework. This flag would then be saved and checked alongside the filter as well.

Do you think that this is something that belongs in the framework? It seems like a pretty common use case and at the moment to do it correctly, you'd need to wrap your subscribers in another subscriber + signal that retains the second to last fired value. If you're interested, I can draft up a pull request (probably with solution 4) and we can see how it looks.

**Comment by artman** [comment]
Hi @DimaVartanian. You're right, this is not something that Signals currently supports, and I don't think it should. It's designed to be a super light eventing framework with no frills. If I had to do it again, I'd even remove the filtering option. For anything more complicated, I'd suggest you use RxSwift, which has a lot more functionality. I'd like to keep Signals as a framework that does very little very good without much overhead, so that it could for example be used in other frameworks as the public-facing API when Rx is simply too overkill.
