### ISSUE TITLE
How to fire() without arguments?

### ISSUE THREAD

**Issue by PierBover** [artman/Signals#54]
Sorry if this is obvious but I'm new to Swift.

I'd like fire a Signal without passing any argument.

I've resorted to using `Signal<Int?>()` and `.fire(nil)` but is there more elegant way of handling this?

**Comment by artman** [comment]
You can do:
```
let signal = Signal<Void>()
signal.fire(())
```

**Comment by PierBover** [comment]
Is there no way to simply do `signal.fire()` ?

**Comment by artman** [comment]
Unfortunately no. In Swift 4 you cannot omit the parameter even when calling a function that takes a void type.
