### ISSUE TITLE
Advice on compiler errors sought

### ISSUE THREAD

**Issue by josephbeuysmum** [artman/Signals#55]
Please see the attached image. I am only seeing these errors after adding the Signals pod to a new Cocoa Touch Framework Swift 4.0 project
<img width="872" alt="screen shot 2018-02-15 at 15 16 28" src="https://user-images.githubusercontent.com/14836799/36264012-830d967e-1263-11e8-9154-a443350228c1.png">
What do you think is the best way of dealing with these, Tuomas?

**Comment by artman** [comment]
You seem to be pulling an older verision, one that isn't compatible with Swift 4. Please update your podfile to pull version 5.0.

**Comment by josephbeuysmum** [comment]
oh. ok. dunno how I managed that. thanks Tuomas
