### ISSUE TITLE
Why doesn't uber use this

### ISSUE THREAD

**Issue by AndrewSB** [artman/Signals#65]
It looks interesting, and definitely smaller than RxSwift. Were there conversations to have uber move to this? Why haven't they?

**Comment by artman** [comment]
We were using it before we switched to Rx. This lib is for people who don't need the complexity of Rx, so its a good alternative for small apps or libraries who don't want to bundle in huge amounts of Rx code.

**Comment by AndrewSB** [comment]
Gotcha, did you speak/write about the benefits of Rx over using these Observables? 

was it primarily the performance of Rx that was preferred? or was it more the DevX?

**Comment by artman** [comment]
Signals is to Rx what a toothpick is to a swiss army knife. I would assume Signals to be more performant becuase it does do a lot less things. And by a lot less I mean a whole lot less. If you don't need features from Rx, use Signals, otherwise use Rx.
