### ISSUE TITLE
Attach-and-forget observation. Feature or bug?

### ISSUE THREAD

**Issue by AndrewSB** [artman/Signals#66]
Attach-and-forget sounds interesting, but how do you deal with the problem of retain cycles and lifetimes that Disposables were created for?

**Comment by netizen01** [comment]
```[weak self]``` is your friend.

**Comment by AndrewSB** [comment]
I understand that I won't capture myself, but how does the subscription know to stop firing?

Concretely, if I have the code:

```swift 
class MyVC {
  func viewDidLoad() {
    NSGlobalTimerEverySecond().subscribe { [weak self] in print("hi") }
  }
}
```

will my print not keep printing up until my app shuts down? Since my view controller doesn't take a disposable, which it would then dispose on deallocation, the global subscription table wouldn't know to stop firing the print.

**Comment by netizen01** [comment]
You have to pass an object to the subscribe function which acts as the observer key. The Signal holds a weak reference to that object and when it is GC'd, the callback block will also go with it.

`
class MyVC {
  func viewDidLoad() {
    NSGlobalTimerEverySecond().subscribe(self) { [weak self] in print("hi") }
  }
}
`

**Comment by AndrewSB** [comment]
Ahh, I see. Thanks @netizen01!
