### ISSUE TITLE
Release a 6.0.0 Cocoapods

### ISSUE THREAD

**Issue by stephanheilner** [artman/Signals#72]
It looks like 6.0.0 was completed and tagged, but never released through CocoaPods. Could we please get that pushed so we can use it? Thanks in advance!

**Comment by stephanheilner** [comment]
@artman I'd really love to use this code, but I need it to support Swift 4.2 because of other dependencies. Would it be possible for you to push a pod update? I'm in a bit of a time-crunch. TIA!

**Comment by artman** [comment]
Sorry, took me a while to get this shipped. I still had problems with OSX not building correctly in pod lib lint, so I temporarily removed it. 6.0.0 is now out.

**Comment by stephanheilner** [comment]
Thanks! What were you trying to do on OSX, or what wasn't working? I can probably help...

**Comment by artman** [comment]
The `s.osx.deployment_target = '10.9'` line in the pod spec (its still there), causes my `pod lib lint` to fail. Just gives a xcodebuild exited with a non-zero exit code failure without any preceding information on the actual failure. Feel free to check it out.

**Comment by stephanheilner** [comment]
It actually works just fine as long as you use CocoPods 1.6.0.rc2. Ever since Xcode 10.1 came out, CocoaPods 1.5.3 fails for most cases when doing a `pod spec lint` or `pod lib lint`.
